### ISSUE TITLE
What is the offset in the input of the model?

### ISSUE THREAD

**Issue by shoushouwang** [LiyaoTang/contrastBoundary#27]
Hi, could you tell me what offset is in the input of the model？
Hope to receive your reply soon.
Thanks!

**Comment by LiyaoTang** [comment]
Hi, thanks for your interest.

Could you provide more detail in your question? E.g. referring to the line of the code.

**Comment by shoushouwang** [comment]
Hi, thanks for your reply.
I mean the word "offset" in line 98 of the pointtransformer_seg.py file. 
What is the data in "Offset" refers to？

**Comment by LiyaoTang** [comment]
Hi,

Since we have multiple point clouds of different sizes in the same batch, we stack them along the 1st axis and thus need to remember the index that starts a new point cloud.

The offset is precisely for this use. You could also check the original point-transformer repo for a better understanding :)
